spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monacolibrary
    username: monaco
    password: Rocobz16
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
